version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: menuly_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: menuly_delivery
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: menuly
      MYSQL_PASSWORD: menuly123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - menuly_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: menuly_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - menuly_network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Django Web Application
  web:
    build: .
    container_name: menuly_web
    restart: unless-stopped
    environment:
      - DEBUG=0
      - DATABASE_HOST=db
      - DATABASE_NAME=menuly_delivery
      - DATABASE_USER=menuly
      - DATABASE_PASSWORD=menuly123
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - menuly_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 menuly.wsgi:application"

  # Celery Worker
  celery:
    build: .
    container_name: menuly_celery
    restart: unless-stopped
    environment:
      - DEBUG=0
      - DATABASE_HOST=db
      - DATABASE_NAME=menuly_delivery
      - DATABASE_USER=menuly
      - DATABASE_PASSWORD=menuly123
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - menuly_network
    command: celery -A menuly worker --loglevel=info

  # Celery Beat (Task Scheduler)
  celery-beat:
    build: .
    container_name: menuly_celery_beat
    restart: unless-stopped
    environment:
      - DEBUG=0
      - DATABASE_HOST=db
      - DATABASE_NAME=menuly_delivery
      - DATABASE_USER=menuly
      - DATABASE_PASSWORD=menuly123
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - menuly_network
    command: celery -A menuly beat --loglevel=info

  # Nginx (opcional - para produção)
  nginx:
    image: nginx:alpine
    container_name: menuly_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    networks:
      - menuly_network

volumes:
  mysql_data:
  redis_data:

networks:
  menuly_network:
    driver: bridge