# Generated by Django 5.2.4 on 2025-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicostatuspedido",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Histórico de Status",
            },
        ),
        migrations.RenameField(
            model_name="historicostatuspedido",
            old_name="data_mudanca",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_anterior",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("novo", "Novo"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_novo",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("novo", "Novo"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("novo", "Novo"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                default="novo",
                max_length=20,
            ),
        ),
    ]
