# Generated by Django 5.0.1 on 2025-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_historicostatuspedido_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_novo",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("saiu_entrega", "Saiu para Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                default="carrinho",
                max_length=20,
            ),
        ),
    ]
