# Generated by Django 5.0.1 on 2025-08-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_historicostatuspedido_status_anterior_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestauranteCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurantes_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="core.restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente do Restaurante",
                "verbose_name_plural": "Clientes do Restaurante",
                "unique_together": {("restaurante", "cliente")},
            },
        ),
    ]
