# Generated by Django 5.0.1 on 2025-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_restaurantecliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="frete_fixo",
            field=models.BooleanField(
                default=False, help_text="Usar valor fixo para o frete?"
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="valor_adicional_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="valor_frete_fixo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="valor_frete_padrao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
