# Generated by Django 5.0.1 on 2025-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_restaurante_frete_fixo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="raio_limite_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Raio máximo de entrega em km",
                max_digits=5,
                null=True,
            ),
        ),
    ]
