# Generated by Django 5.0.1 on 2025-08-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_restaurante_raio_limite_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurante",
            name="mensagem_boas_vindas",
            field=models.TextField(
                blank=True,
                help_text="Mensagem de boas-vindas exibida na página inicial",
            ),
        ),
    ]
