# Generated by Django 5.0.1 on 2025-08-20 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_restaurante_mensagem_boas_vindas"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="controlar_estoque",
            field=models.BooleanField(
                default=False, help_text="Ativar controle de estoque para este produto"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque_atual",
            field=models.PositiveIntegerField(
                default=0, help_text="Quantidade atual em estoque"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque_minimo",
            field=models.PositiveIntegerField(
                default=5, help_text="Estoque mínimo para alerta"
            ),
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pedido_novo", "Novo Pedido"),
                            ("estoque_baixo", "Estoque Baixo"),
                            ("estoque_esgotado", "Estoque Esgotado"),
                            ("sistema", "Mensagem do Sistema"),
                            ("avaliacao", "Nova Avaliação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                (
                    "link_acao",
                    models.CharField(
                        blank=True,
                        help_text="Link para ação relacionada (opcional)",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="core.restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "notificacoes",
                "ordering": ["-created_at"],
            },
        ),
    ]
