# Generated by Django 5.0.1 on 2025-08-21 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_produto_controlar_estoque_produto_estoque_atual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("multi", "Multi-Loja"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título exibido para o usuário", max_length=100
                    ),
                ),
                ("descricao", models.TextField()),
                ("preco_mensal", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "preco_setup",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taxa de configuração inicial",
                        max_digits=8,
                    ),
                ),
                (
                    "limite_pedidos_mes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null = ilimitado", null=True
                    ),
                ),
                (
                    "limite_produtos",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null = ilimitado", null=True
                    ),
                ),
                ("limite_funcionarios", models.PositiveIntegerField(default=1)),
                ("limite_lojas", models.PositiveIntegerField(default=1)),
                ("permite_pagamento_online", models.BooleanField(default=False)),
                ("permite_cupons_desconto", models.BooleanField(default=False)),
                ("permite_whatsapp_bot", models.BooleanField(default=False)),
                ("permite_impressao_termica", models.BooleanField(default=True)),
                ("permite_relatorios_avancados", models.BooleanField(default=False)),
                ("permite_api_integracao", models.BooleanField(default=False)),
                ("permite_area_entregador", models.BooleanField(default=False)),
                ("permite_multi_loja", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordem_exibicao",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem para exibição nos preços"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Destacar como plano recomendado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plano de Assinatura",
                "verbose_name_plural": "Planos de Assinatura",
                "ordering": ["ordem_exibicao", "preco_mensal"],
            },
        ),
        migrations.AddField(
            model_name="restaurante",
            name="data_inicio_plano",
            field=models.DateField(
                blank=True, help_text="Data de início da assinatura", null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="data_vencimento_plano",
            field=models.DateField(
                blank=True, help_text="Data de vencimento da mensalidade", null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="plano_ativo",
            field=models.BooleanField(
                default=True, help_text="Se false, restaurante fica suspenso"
            ),
        ),
        migrations.AddField(
            model_name="restaurante",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                help_text="Plano de assinatura do restaurante",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.plano",
            ),
        ),
    ]
