# Generated by Django 5.0.1 on 2025-08-25 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_popular_planos_iniciais"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_entrega",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor pago ao entregador",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("aguardando_entregador", "Aguardando Entregador"),
                    ("em_entrega", "Em Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicostatuspedido",
            name="status_novo",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("aguardando_entregador", "Aguardando Entregador"),
                    ("em_entrega", "Em Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("carrinho", "No Carrinho"),
                    ("pendente", "Pendente de Pagamento"),
                    ("confirmado", "Confirmado"),
                    ("preparando", "Preparando"),
                    ("pronto", "Pronto"),
                    ("aguardando_entregador", "Aguardando Entregador"),
                    ("em_entrega", "Em Entrega"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                    ("devolvido", "Devolvido"),
                ],
                default="carrinho",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("funcionario", "Funcionário"),
                    ("gerente", "Gerente"),
                    ("lojista", "Lojista"),
                    ("entregador", "Entregador"),
                    ("superadmin", "Super Admin"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Entregador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "cnh",
                    models.CharField(
                        blank=True, help_text="Número da CNH", max_length=20
                    ),
                ),
                (
                    "veiculo",
                    models.CharField(
                        blank=True, help_text="Ex: Moto Honda CG 160", max_length=50
                    ),
                ),
                (
                    "dados_bancarios",
                    models.CharField(
                        blank=True, help_text="Dados para pagamento", max_length=100
                    ),
                ),
                (
                    "disponivel",
                    models.BooleanField(
                        default=True, help_text="Disponível para receber pedidos"
                    ),
                ),
                (
                    "em_pausa",
                    models.BooleanField(default=False, help_text="Em pausa temporária"),
                ),
                (
                    "nota_media",
                    models.FloatField(default=0, help_text="Média das avaliações"),
                ),
                ("total_avaliacoes", models.PositiveIntegerField(default=0)),
                ("total_entregas", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entregador",
                "verbose_name_plural": "Entregadores",
                "db_table": "entregadores",
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoEntregador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao_entregador",
                        to="core.pedido",
                    ),
                ),
                (
                    "entregador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="core.entregador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação do Entregador",
                "verbose_name_plural": "Avaliações dos Entregadores",
                "db_table": "avaliacoes_entregador",
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="entregador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_entrega",
                to="core.entregador",
            ),
        ),
        migrations.CreateModel(
            name="OcorrenciaEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cliente_ausente", "Cliente ausente"),
                            ("endereco_errado", "Endereço incorreto"),
                            ("pagamento_recusado", "Pagamento recusado"),
                            ("produto_danificado", "Produto danificado"),
                            ("atraso_restaurante", "Atraso do restaurante"),
                            ("transito_intenso", "Trânsito intenso"),
                            ("veiculo_quebrado", "Problema com veículo"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Descreva detalhadamente a ocorrência"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("resolvido", models.BooleanField(default=False)),
                ("observacoes_resolucao", models.TextField(blank=True)),
                (
                    "entregador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.entregador",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência de Entrega",
                "verbose_name_plural": "Ocorrências de Entrega",
                "db_table": "ocorrencias_entrega",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="AceitePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aceite", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aceito", "Aceito"),
                            ("recusado", "Recusado"),
                            ("expirado", "Expirado"),
                        ],
                        default="aceito",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aceites",
                        to="core.pedido",
                    ),
                ),
                (
                    "entregador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aceites",
                        to="core.entregador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aceite de Pedido",
                "verbose_name_plural": "Aceites de Pedidos",
                "db_table": "aceite_pedidos",
                "unique_together": {("pedido", "entregador")},
            },
        ),
    ]
