# Generated by Django 5.0.1 on 2025-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_pedido_valor_entrega_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcaopersonalizacao",
            name="quantidade_maxima",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantidade máxima de itens que podem ser selecionados (apenas para checkbox). Deixe vazio para ilimitado",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opcaopersonalizacao",
            name="quantidade_minima",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Quantidade mínima de itens que devem ser selecionados (apenas para checkbox)",
            ),
        ),
    ]
