# Generated by Django 5.0.1 on 2025-09-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_opcaopersonalizacao_quantidade_maxima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="permite_meio_a_meio",
            field=models.BooleanField(
                default=False,
                help_text="Permite vender este produto como metade de uma pizza",
            ),
        ),
    ]
