# Generated by Django 5.0.1 on 2025-09-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_produto_permite_meio_a_meio"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="meio_a_meio",
            field=models.JSONField(
                blank=True, help_text="Dados da pizza meio-a-meio", null=True
            ),
        ),
    ]
