# Generated by Django 5.0.1 on 2025-09-09 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_itempedido_meio_a_meio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sessao_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da sessão para usuários não logados",
                        max_length=40,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinhos",
                        to="core.restaurante",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinhos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrinho",
                "verbose_name_plural": "Carrinhos",
                "db_table": "carrinhos",
            },
        ),
        migrations.CreateModel(
            name="CarrinhoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "dados_personalizacao",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dados de personalização incluindo meio-a-meio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Carrinho",
                "verbose_name_plural": "Itens do Carrinho",
                "db_table": "carrinho_itens",
            },
        ),
        migrations.CreateModel(
            name="CarrinhoItemPersonalizacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opcao_nome", models.CharField(max_length=100)),
                ("item_nome", models.CharField(max_length=100)),
                (
                    "preco_adicional",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "carrinho_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizacoes",
                        to="core.carrinhoitem",
                    ),
                ),
                (
                    "item_personalizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.itempersonalizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personalização do Item do Carrinho",
                "verbose_name_plural": "Personalizações dos Itens do Carrinho",
                "db_table": "carrinho_item_personalizacoes",
            },
        ),
        migrations.AddIndex(
            model_name="carrinho",
            index=models.Index(
                fields=["usuario", "restaurante"], name="carrinhos_usuario_0a79ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrinho",
            index=models.Index(
                fields=["sessao_id", "restaurante"], name="carrinhos_sessao__c92d39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carrinhoitem",
            index=models.Index(
                fields=["carrinho", "produto"], name="carrinho_it_carrinh_3093f4_idx"
            ),
        ),
    ]
