# Generated by Django 5.0.1 on 2025-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_carrinho_carrinhoitem_carrinhoitempersonalizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregador",
            name="percentual_comissao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual de comissão sobre o pedido",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entregador",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[
                    ("fixo", "Valor Fixo"),
                    ("fixo_comissao", "Fixo + Comissão"),
                    ("comissao", "Apenas Comissão"),
                ],
                default="fixo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entregador",
            name="valor_fixo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor fixo por entrega",
                max_digits=8,
                null=True,
            ),
        ),
    ]
