# Generated by Django 5.0.1 on 2025-08-20 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_restaurante_raio_limite_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impressora",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da impressora (ex: Impressora Cozinha)",
                        max_length=100,
                    ),
                ),
                (
                    "tipo_conexao",
                    models.CharField(
                        choices=[
                            ("usb", "USB"),
                            ("rede", "Rede/Ethernet"),
                            ("wifi", "Wi-Fi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP da impressora (para conexões de rede)",
                        null=True,
                    ),
                ),
                (
                    "porta",
                    models.PositiveIntegerField(
                        default=9100, help_text="Porta da impressora"
                    ),
                ),
                (
                    "caminho_usb",
                    models.CharField(
                        blank=True,
                        help_text="Caminho USB (ex: /dev/usb/lp0)",
                        max_length=200,
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "padrao_para_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("balcao", "Balcão"),
                            ("delivery", "Delivery"),
                            ("cozinha", "Cozinha"),
                            ("geral", "Geral"),
                        ],
                        help_text="Tipo de pedido para o qual esta impressora é padrão",
                        max_length=10,
                    ),
                ),
                (
                    "largura_papel",
                    models.PositiveIntegerField(
                        default=80, help_text="Largura do papel em mm"
                    ),
                ),
                (
                    "cortar_papel",
                    models.BooleanField(
                        default=True, help_text="Cortar papel após impressão"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressoras",
                        to="core.restaurante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impressora",
                "verbose_name_plural": "Impressoras",
                "db_table": "impressoras",
                "unique_together": {("restaurante", "padrao_para_tipo")},
            },
        ),
    ]
